- name: Install neovim from appimage
  block:
    - name: Ensure config dir
      file:
        path: "{{ nvim_local_bin_dir }}"
        state: directory
        owner: "{{ nvim_user }}"
        mode: 0751
    - name: Download
      get_url:
        url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
        dest: "{{ nvim_local_bin_dir }}/nvim"
        mode: 0711
        owner: "{{ nvim_user }}"
