- name: Install neovim from appimage
  block:
    - name: Ensure config dir
      file:
        path: "{{ nvim_local_bin_dir }}"
        state: directory
        owner: "{{ nvim_user }}"
        mode: 0751
    - name: Download
      get_url:
        url: "https://github.com/neovim/neovim/releases/{{ nvim_version }}/download/nvim.appimage"
        dest: "{{ nvim_local_bin_dir }}/nvim"
        mode: 0755
        owner: "{{ nvim_user }}"

- name: Update Alternative
  community.general.alternatives:
    name: "{{ item }}"
    path: "{{ nvim_install_dir }}"
    priority: 110
  loop:
  - ex
  - vi
  - view
  - vim
  - vimdiff
  - nvim
  when: have_root | default(true) | bool
