- name: Nvim deps
  apt:
    name: "{{ item }}"
  become: true
  become_user: root
  with_items:
    - python3-dev
    - python3-pip

- name: Install with apt
  apt:
    name: neovim
    state: latest
  when: nvim_version | string == "latest"

- name: "Install version: {{ nvim_version }}"
  apt:
    name: "neovim={{ nvim_version }}"
    state: present
  when: nvim_version | string != "latest"
