- name: Clean existing file or conf dir for Vim/Nvim
  block:
    - name: Clean files
      file:
        name: "{{ item }}"
        state: absent
      with_items:
        - "{{ nvim_autoload_dir }}"
        - "{{ vim_autoload_dir }}"
        - "{{ nvim_conf_dir }}"
        - "{{ nvim_conf }}"
        - "{{ vim_conf }}"
      tags:
        - configuration
    - name: Clean apt
      apt:
        name: neovim
        state: absent
      become: true
      become_user: root
      tags:
        - apt
  always:
    - name: Clean appimage
      file:
        name: "{{ nvim_local_bon_dir }}/nvim"
        state: absent
      tags:
        - appimage
  tags:
    - clean
    - remove
