- name: Install deps
  become: true
  block:
    - name: Apt
      apt:
        name: "{{ item }}"
      with_items:
        - ninja-build
        - gettext
        - libtool
        - libtool-bin
        - autoconf
        - automake
        - cmake
        - git
        - g++
        - pkg-config
        - unzip
        - curl
        - doxygen
      when: ansible_os_family == "Debian"
    - name: Install dnf
      yum:
        name: dnf-plugins-core
      when: ansible_os_family == "RedHat"
    - name: Enabled powertools
      command: yum config-manager --set-enabled powertools
      args:
        warn: no
      changed_when: false
      when: ansible_os_family == "RedHat"
    - name: Yum
      yum:
        name:
          - libtool
          - autoconf
          - automake
          - cmake
          - git
          - gcc
          - gcc-c++
          - make
          - pkgconfig
          - unzip
          - patch
          - gettext
          - ninja-build
          - curl
        state: present
      when: ansible_os_family == "RedHat"
  tags:
    - deps
  when: have_root | default(true) | bool

- name: Install from source
  block:
    - name: Get source
      ansible.builtin.git:
        repo: https://github.com/neovim/neovim
        dest: "{{ nvim_source_dest }}"
        version: "{{ nvim_source_version }}"
    - name: Build nvim
      community.general.make:
        chdir: "{{ nvim_source_dest }}"
        params:
          CMAKE_BUILD_TYPE: "{{ nvim_source_build_mode }}"
          CMAKE_INSTALL_PREFIX: "{{ nvim_local_bin_dir | dirname }}"
      changed_when: false
    - name: Install
      community.general.make:
        chdir: "{{ nvim_source_dest }}"
        target: "install"
      changed_when: false
