- name: Install neovim
  block:
    - include_tasks: package.yml
      tags:
        - package
        - deps
      when: nvim_installation|string == "package"
    - include_tasks: appimage.yml
      tags:
        - appimage
      when: nvim_installation|string == "appimage"
    - include_tasks: compile.yml
      tags:
        - source
      when: nvim_installation|string == "source"
  tags:
    - install

- name: Add python support
  include_tasks: python_support.yml
  tags:
    - python_support

- name: Prepare config
  include_tasks: configuration.yml 
  tags:
    - bootstrap
