- name: Install neovim
  block:
    - include_tasks: apt.yml
      become: true
      become_user: root
      tags:
        - apt
  rescue:
    - name: Set install to appimage
      set_fact:
        skip_appimage: true
  block:
    - include_tasks: appimage.yml
      when: skip_appimage is undefined
      tags:
        - appimage
  tags:
    - install
    - deps

- name: Config
  block:
    - name: Make configuration dir
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ nvim_conf_dir }}"
        - "{{ vim_autoload_dir }}"
        - "{{ nvim_autoload_dir }}"
    - name: Install vim.plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ vim_autoload_dir }}/plug.vim"
        force: yes
      tags:
        - vimplug
        - plugins
    - name: Install python nvim plugin
      pip: 
        name: neovim 
        executable: pip3
        state: latest
        extra_args: --user
      ignore_errors: true
    - name: Configure nvim
      template:
        src: init.vim
        dest: "{{ nvim_conf }}"
    - name: Copy autoload between vim & nvim
      file:
        src: "{{ vim_autoload_dir }}"
        path: "{{ nvim_autoload_dir | dirname }}"
      tags:
        - symlink
    - name: Share Conf
      file:
        src: "{{ vim_conf }}"
        dest: "{{ nvim_conf }}"
        state: link
      ignore_errors: true
      tags:
        - symlink
    - name: Init vim plug
      shell:
        cmd: vim "+silent! PlugInstall!" +qall!
      tags:
        - plugins
    - name: Init nvim plug
      shell:
        cmd: nvim "+silent! PlugInstall!" +qall!
      tags:
        - plugins
  tags:
    - bootstrap
