- name: Nvim deps
  yum:
    name:
      - python3-devel
      - python3-pip
      - epel-release
    state: present
  become: true

- name: Install with yum
  yum:
    name: neovim
    state: latest
  become: true
  when: nvim_version | string == "latest"

- name: "Install version: {{ nvim_version }}"
  yum:
    name: "neovim-{{ nvim_version }}"
    state: present
  become: true
  when: nvim_version | string != "latest"

- name: Extra deps
  yum:
    name: python3-neovim
    state: present
  become: true
  become_user: root
