---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "${MOLECULE_DISTRO_NAME:-Ubuntu18}"
    image: "${MOLECULE_DISTRO_IMAGE:-ubuntu:18.04}"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
