---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python for Ansible
      raw: |
              test -e /usr/bin/python || \
              (test -e /usr/bin/apt && (apt -y update && apt install -y python3-minimal python3-pip)) || \
              (test -e /usr/bin/yum && (yum -y install libselinux-python3)) || \
              echo "No package manager found"
      changed_when: false

- name: Sudoer
  hosts: all
  tasks:
    - name: Install sudo
      package:
        name: sudo
      changed_when: false
